import type { Metadata } from "next";

import { roboto_mono, gloria, freehand } from "@/lib/fonts"

// import style files
import "../styles/globals.css";
import "../styles/fonts.css"
import "../styles/colors.css"
import "../styles/elevation.css"

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";

import Nav from "@/components/nav";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "mstflotfy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={`${roboto_mono.variable} ${freehand.variable}`}
    >
      <body
        className={cn(
          "min-h-screen antialiased",
          roboto_mono.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <Nav />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
